### ISSUE TITLE
Partials are not getting resolved

### ISSUE THREAD

**Issue by yohangz** [mixmaxhq/rollup-plugin-handlebars-plus#11]
I'm getting the following error with partials.

`'_template.hbs' is imported by src/templates/base.hbs, but could not be resolved – treating it as an external dependency`

While going through the code i noticed that this plugin is just adding the import for partials but not resolving them which is causing this issue.

**Comment by wearhere** [comment]
Hey @yohangz, we use partials in our code so I'm _pretty_ sure this works. :)

You're right that the plugin doesn't compile partials in the same pass as templates. But my colleague and I believe that the plugin is invoked by Rollup recursively, i.e. if the output includes `import` statements Rollup will resolve and transform those as well.

My guess would be that `'_template.hbs'` isn't a valid module identifier. That is, Rollup / this plugin would equally fail to resolve a "top-level" template with that name. If you don't wish to name your partial with a full file path (Rollup's default for locating plugins), you can register the partial's directory with `rollup-plugin-root-import`—see this plugin's [example](https://github.com/mixmaxhq/rollup-plugin-handlebars-plus#usage) and the documentation on `partialRoots` there.

**Comment by yohangz** [comment]
Hi @wearhere, Thanks for the quick detailed response. I found the actual issue, it was not working when used with typescript plugin. Fix was to add relative partial imports with `./_template.hbs`
