### ISSUE TITLE
Compile with older version of handlebars

### ISSUE THREAD

**Issue by btamas** [mixmaxhq/rollup-plugin-handlebars-plus#13]
Is there a way to use older version of handlebars to build templates?
I used webpack before and `package.json` in `handlebars-loader` contains handlebars only as a `peerDependency` so I can install my version. Is it possible to add this feature here as well or is this plugin really depend on handlebars version 4?

package.json in `handlebars-loader`
```
"peerDependencies": {
    "handlebars": ">= 1.3.0 < 5"
  },
```

**Comment by btamas** [comment]
I forked this package. Added `handlebars` as peerDependency and I installed `handlebars@1.3.0`. Everything works in my environment except this line: https://github.com/mixmaxhq/rollup-plugin-handlebars-plus/blob/master/src/index.js#L61
If I comment it out, I have no other issue and I get my precompiled code.

**Comment by btamas** [comment]
I tested with different versions and the plugin works without code modification with handlebars version 3 or above. I created a pull request where I added handlebars as a peerDependency, so plugin users will be able to install their preferred version.

**Comment by wearhere** [comment]
Thanks @btamas ! Left some comments on your PR, #14 .

**Comment by btamas** [comment]
Issue solved with merge of https://github.com/mixmaxhq/rollup-plugin-handlebars-plus/pull/14
