### ISSUE TITLE
Getting pre fix of "export default " along with pre compile return.

### ISSUE THREAD

**Issue by prabintp** [mixmaxhq/rollup-plugin-handlebars-plus#17]
Getting pre fix of "export default " along with pre compile return.

 Template$1 = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "**export default** \"<div class=\\\"c-sm-2 c-md-2 c-lg-2 date\\\">"
    + container.escapeExpression((helpers.customDateFormat || (depth0 && depth0.customDateFormat) || helpers.helperMissing).call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? depth0.date : depth0),{"name":"customDateFormat","hash":{},"data":data}))
    + "</div>\";";
},"useData":true});
function transhistoryRecord(data, options, asString) {
  var html = Template$1(data, options);
  return (asString || true) ? html : $(html);
}

**Comment by btamas** [comment]
@prabintp Could you please comment your hbs template?

**Comment by skeggse** [comment]
This seems like it might be because another plugin is transforming the template first. If you provide a complete reproducible example, we might be able to figure out a workaround.
